CREATE USER ${ORACLE_SWMS_USER} IDENTIFIED BY "${ORACLE_SWMS_PASSWORD}";
GRANT CREATE SESSION TO ${ORACLE_SWMS_USER};
GRANT CREATE USER TO ${ORACLE_SWMS_USER};
GRANT DROP USER TO ${ORACLE_SWMS_USER};
GRANT CONNECT, SWMS_VIEWER, SWMS_USER TO ${ORACLE_SWMS_USER} WITH ADMIN OPTION;
