DECLARE
USEREXIST INTEGER;
BEGIN
  SELECT COUNT(*) INTO USEREXIST FROM DBA_USERS WHERE USERNAME = '${ORACLE_SWMS_USER}';
  IF (USEREXIST > 0) THEN
    EXECUTE IMMEDIATE 'DROP USER ${ORACLE_SWMS_USER}';
  END IF;
END;
/
